GET http://localhost:3003/api/users
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ4eCIsImlkIjoiNjJhOTc5YmEyYjc4YTcxOTBhNjE0MzNjIiwiaWF0IjoxNjU1Mjk2OTU4fQ.M1lqpq4Ye72NXca5zTG1YJdhgDrA1zDZr_4UMXsxjKg